# Numpy 배열

In [7]:
import numpy as np # 1차원 배열 만들기

arr = np.array([0,1,2,3,4,5,6,7,8,9])

print(arr) # 공백으로 구분되는 것을 확인할 수 있음.

print(type(arr))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [9]:
arr = np.array([[1,2,3],[3,4,5]]) # 2차원 배열 만들기

print(arr) 

len(arr) #행의 개수

len(arr[0]) #열의 개수

[[1 2 3]
 [3 4 5]]


3

# Numpy 배열의 차원과 크기

In [12]:
arr = np.array([1,2,3])
print(arr.ndim) # 배열의 차원
print(arr.shape) # shape 속성



1
(3,)


In [17]:
na = np.arange(12)   # Reshape

print(na)

nb = na.reshape(3,4) # 2차원 - 3행 4열의 크기로 변경함.
print(nb)

nb = na.reshape(3,-1) # 자동으로 계산
print(nb)

nb = na.reshape(2,2,-1) # 3차원의 배열로 x,y 크기를 지정후 z 크기는 자동으로 변경함.
print(nb)

nb = na.reshape(2,-1,2) # y 크기를 자동으로 변경함
print(nb)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [18]:
nc =  nb.flatten() #flatten은 원본을 변경해도 같이 변경되지 않음.
print(nc)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
