#1. Numpy 모듈 소개

###1-0 Numpy 모듈 임폴트

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>

### 1-1. 별칭 (alias) 지정하기 일반적으로 np

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>

## 2. ndarray 생성하기

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
a = [1, 2, 3, 4]
a

[1, 2, 3, 4]

numpy.ndarray

### 2-1. list로 부터 생성하기

In [ ]:
mylist1 = [1, 2, 3, 4]

In [ ]:
arr1 = np.array(mylist1)

In [ ]:
# list로 2차원 ndarray 생성


[[1, 2, 3, 4], [5, 6, 7, 8]]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 2-2. shape확인하기

In [ ]:
#arr1의 shape 확인


(4,)

In [ ]:
#arr2의 shape 확인


(2, 4)

## 3. array에서의 data 타입
[numpy data type 살펴보기](https://engineer-mole.tistory.com/85)

array에서는 list와는 다르게 1개의 **단일 데이터 타입**만 허용 됨.  
타입이 다른 형태 데이터를 넣어서 ndarray 객체를 만들면 어떻게 될까?

### 3-1. list에서의 data 타입

In [ ]:
mylist = [1, 3.14, '테디', '1234']

In [ ]:
mylist

In [ ]:
# mylist 인덱스 1의 값 확인


In [ ]:
# mylist 인덱스 2의 값 확인


### 3-2. array에서의 data 타입 결정 (case별로 살펴보기)

### case 1. int와 float 타입이 혼재된 경우

In [ ]:
arr = np.array([1, 2, 3, 3.14])

In [ ]:
arr

array([1.  , 2.  , 3.  , 3.14])

### case 2. int와 float 타입이 혼재되었으나, dtype을 지정한 경우

In [ ]:
# dtype=int 옵션 파라미터로 정수형으로 입력


array([1, 2, 3, 3])

### case 3. int와 str 타입이 혼재된 경우

In [ ]:
arr = np.array([1, 3.14, '테디', '1234'])

In [ ]:
arr

array(['1', '3.14', '테디', '1234'], dtype='<U32')

In [ ]:
# arr[0], arr[1] + 연산 확인


'13.14'

### case 4. int와 str 타입이 혼재되어 있고 int로 dtype을 지정한 경우

In [ ]:
arr = np.array([1, 3.14, '1234'], dtype=int)

In [ ]:
 arr

array([   1,    3, 1234])

In [ ]:
# 문자열이 같이 들어간 경우는 어떻게 될까?
arr = np.array([1, 3.14, '1234','colab'], dtype=int)

#4. 슬라이싱(Slicing)
배열의 부분을 추출하는 기능

In [ ]:
import numpy as np

In [ ]:
arr = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
# ndarray 형태 확인하기


(10,)

###3-1 index 지정하여 indexing(색인)하기

#### 1차원 ndarray 요소 확인
arr[인덱스]  
arr[인덱스], arr[인덱스]

In [ ]:
arr[0]

10

14

In [ ]:
# 인덱스 10의 값 확인


In [ ]:
# arr의  0과 5의 인덱스 확인


In [ ]:
# arr의  -1과 6의 인덱스 확인


In [ ]:
# arr의  -10과 -6의 인덱스 확인


In [ ]:
# arr의  -11 인덱스 확인
arr[-11]

####2차원 array

In [ ]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [ ]:
# arr2d 객체의 shape 확인하기


(3, 4)

#### 2차원 ndarray 요소 확인
arr2d[행 인덱스, 열 인덱스]

In [ ]:
# 3 행 전체


array([ 9, 10, 11, 12])

In [ ]:
# 인덱스 (0, 2) 요소


3

In [ ]:
# 인덱스 (2, 1) 요소

10

In [ ]:
# arr2d[2, 3], arr2d[0, 2] 확인해 보기


(12, 3)

In [ ]:
# 특정 위치에 값 변경
# 인덱스 (2,3)에 값 12->13으로 변경


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 13]])

#### 3차원 array는?

In [ ]:
arr3d = np.array([[[1, 2,],[3, 4]], 
                  [[5, 6], [7, 8]], 
                  [[9, 10], [11, 12]]])

In [ ]:
arr3d

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
arr3d.shape

(3, 2, 2)

### 3-2 범위 색인

####1차원
- arr[start:stop:step]
- arr[::-1] # step이 음수인 경우 거꾸로 출력

In [2]:
import numpy as np

In [3]:
arr = np.arange(10,20)

In [4]:
arr2 = [20,40,65,80,30,10,65,55]

In [5]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
# 정렬이 아닌 순서를 거꾸로 하는 것
arr2[::-1]

[55, 65, 10, 30, 80, 65, 40, 20]

In [ ]:
# index 1이상 끝까지
arr[1:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
# 처음 ~ (5-1)까지(5에서 stop)


array([10, 11, 12, 13, 14])

In [ ]:
# index 1 ~ (5-1)까지
# array([11, 12, 13, 14])


array([11, 12, 13, 14])

In [ ]:
# 처음 ~ (마지막-1)까지(마지막에서 stop)
# 결과 : array([10, 11, 12, 13, 14, 15, 16, 17, 18])


In [ ]:
#arr[start:stop:step]
# 결과 : array([10, 12, 14])


In [ ]:
# 결과 : (array([10, 12, 14]), array([10, 11]))


#### 2차원
  
arr2d[행start:행stop, 열start:열stop]

In [ ]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [ ]:
# 인덱스 0 row(행) 모두 슬라싱하기
# array([1, 2, 3, 4])


array([1, 2, 3, 4])

In [ ]:
# 인덱스 2 column(열) 모두 슬라이싱하기
# array([ 3,  7, 11])


array([ 3,  7, 11])

In [ ]:
# 부분적으로 슬라이싱하기
# array([[1, 2, 3, 4], 
#       [5, 6, 7, 8]])


In [ ]:
# 부분적으로 슬라이싱하기
# array([[3, 4],
#       [7, 8]])


#### 문제. 다음과 같이 슬라이싱하기
- 행 : 1~3행까지, 열 : 1부터 모두


In [ ]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [ ]:
#array([[ 6,  7,  8],
#       [10, 11, 12]])


# 5. Fancy 인덱싱
fancy 인덱싱은 범위가 아닌 **특정 index의 값들을 추출**하고 싶을 때 사용  
index list 업하여 적용하면 값을 추출할 수 있음  
arr[[index list]]

### 5-1 1차원 fancy 인덱싱

In [ ]:
arr = np.array([10, 23, 2, 7, 90, 65, 32, 66, 70])

In [ ]:
# index를 list로 정의 해서 값을 추출
arr[[1, 2, 5]]

array([23,  2, 65])

In [ ]:
# index list를 idx 변수에 대입하여 추출
# array([23,  2, 65])



array([23,  2, 65])

### 5-2. 2차원 fancy 인덱싱

arr2d[[요소1의 행, 요소2의 행], [요소1의 열, 요소2의 열]]

In [ ]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [ ]:
# arr2d[[행index],[열index]]
# array([[ 1,  2,  3,  4],
#       [ 9, 10, 11, 12]])


In [ ]:
# array([[ 2,  4],
#       [ 6,  8],
#       [10, 12]])


In [ ]:
# arr2d[[요소1의 행,요소2의 행],[요소1의 열, 요소2의 열]]
# array([ 6, 11,  2])


#6. Boolean index
조건 필터링을 통하여 Boolean 값으로 색인

###6-1 True와 False 값으로 색인하기

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60])
arr

array([10, 20, 30, 40, 50, 60])

In [ ]:
TFset = [True, False, True]

In [ ]:
# 이렇게 하면 될까요?
arr[TFset]

In [ ]:
# boolean 값을 list로 작성하여 색인, 배열의 갯수가 맞아야함.
# 결과 : array([10, 30, 40, 60])


array([10, 30, 40, 60])

2차원 boolean index

In [ ]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [ ]:
# boolean list로 정의, 행단위로 정의
TFset = [True,False,True]

In [ ]:
#array([[ 1,  2,  3,  4],
#       [ 9, 10, 11, 12]])


### 6-2 조건 필터
비교 연산자를 활용하여 필터를 생성 함
- arr2d[조건필터]

In [ ]:
# ndarray 조건식
# ndarray에 조건식을 주면 boolean 값 반환
arr2d > 2

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
# arr2d[조건필터]
arr2d[ arr2d > 2 ]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
arr2d[ arr2d < 5 ]

array([1, 2, 3, 4])

[문제] 다음을 완성해 보세요. 
- shape (3,2,4) ndarray를 만든다. 데이터는 1~24까지 다양하게 들어가도록 한다.
- 조건필터 : 11보다 큰값 출력


In [ ]:
arr3d = [[[1,2,3,4],
         [5,6,7,8]],
         [[9,10,11,12],
         [13,14,15,4]],
         [[5,6,7,8],
         [9,10,11,12]]]
arr3d = np.array(arr3d)

In [ ]:
# shape 출력 


(3, 2, 4)

array([12, 13, 14, 15, 12])

-----------
# 2차원 boolindex 부연설명

각 names의 성분(7개 열)에 따라 ---> data의 각 행 대응된다고 생각해 보자.  
예를 들어 aaa라는 사람은 1행, bbb는 2행에 대응 된다고 생각하고 아래처럼 array 조건문을 입력해 보자

In [8]:
names = np.array(["aaa", "bbb","ccc", "ddd", "eee", "fff", "ggg"])
data = np.random.rand(7,4)

In [14]:
names

array(['aaa', 'bbb', 'ccc', 'ddd', 'eee', 'fff', 'ggg'], dtype='<U3')

In [13]:
data

array([[0.70412234, 0.1051641 , 0.90924685, 0.61497472],
       [0.90230754, 0.17401736, 0.43687024, 0.99903732],
       [0.48169292, 0.410346  , 0.20613698, 0.2223068 ],
       [0.96355469, 0.1454321 , 0.41573014, 0.9797085 ],
       [0.44719536, 0.89679357, 0.20846717, 0.99125197],
       [0.64939105, 0.46332717, 0.05419308, 0.21729012],
       [0.98127276, 0.39942914, 0.02701573, 0.363234  ]])

In [15]:
names == "aaa"

array([ True, False, False, False, False, False, False])

In [10]:
data[names == "aaa", :]

array([[0.70412234, 0.1051641 , 0.90924685, 0.61497472]])

In [11]:
names =="ccc"

array([False, False,  True, False, False, False, False])

In [12]:
data[names=="ccc", :]

array([[0.48169292, 0.410346  , 0.20613698, 0.2223068 ]])

[문제] 'ggg'에 대응되는 값을 추출해 보세요.