In [ ]:
import numpy as np

## 1. Element-wise operations

numpy는 기본적으로 array 간의 사칙연산을 지원  
행과 열이 같은 배열을 계산하면 같은 위치에 있는 값들이 서로 계산됨  
이런 현상을 Element-wise operations이라 하며 Shape이 같을 때 발생함.  




### 1-1. 덧셈(+)

In [ ]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [ ]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

array([[4, 6, 8],
       [3, 5, 7]])

In [ ]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [ ]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [ ]:
# 가능 할까요?


ValueError: ignored

### 1-2. Sum - matrix 안에서 sum

In [ ]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

array([3, 5, 7])

array([6, 9])

## 2. 행렬 - 뺄셈(-)

In [ ]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [ ]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

array([[-2, -2, -2],
       [ 1,  1,  1]])

In [ ]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [ ]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [ ]:
# shape +, -, * shape이 같아야 함.
a - b

ValueError: ignored

## 곱셈 연산(*) / 나누기(/)

In [ ]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [ ]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

((2, 3), (2, 3))

array([[ 3,  8, 15],
       [ 2,  6, 12]])

array([[0.33333333, 0.5       , 0.6       ],
       [2.        , 1.5       , 1.33333333]])

#2. 행렬의 곱셈 연산은 dot product 사용, 이점 유의하세요!  
- dot product : 내적 

In [ ]:
a = np.array([[1, 2, 3],
              [1, 2, 3], 
              [2, 3, 4]])

In [ ]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [ ]:
a.shape, b.shape

((3, 3), (3, 2))

array([[22, 28],
       [22, 28],
       [31, 40]])

In [ ]:
a.dot(b)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [ ]:
1*1 + 2*3 + 3*5

22

In [ ]:
1*2 + 2*4 + 3*6

28

# 4. transpose(전치 행렬)

In [ ]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

array([[1, 3, 5],
       [2, 4, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

# 5. Broadcasting 

### 5-1 숫자의 연산(단일)

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [ ]:
b = np.array([[3, 3, 3], 
              [3, 3, 3]])

In [ ]:
#a+b


array([[4, 6, 8],
       [3, 5, 7]])

In [ ]:
#a+3


array([[4, 5, 6],
       [5, 6, 7]])

In [ ]:
#a-3


array([[-2, -1,  0],
       [-1,  0,  1]])

In [ ]:
#a*3


array([[ 3,  6,  9],
       [ 6,  9, 12]])

In [ ]:
#a/3


array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 1.        , 1.33333333]])

### 5-2 array(배열)의 브로드캐스팅
일정 조건을 부합하는 다른 형태의 배열끼리 연산을 수행하는 것을 의미  
1. 맴버가 하나인 배열은 어떤 배열에나 브로드캐스팅(Broadcasting)이 가능(단, 맴버가 하나도 없는 빈 배열을 제외)  
ex) 3x4 + 1

2. 하나의 배열의 차원이 1인 경우 브로드캐스팅(Broadcasting)이 가능  
ex) 4x4 + 1x4

3. 차원의 짝이 맞을 때 브로드캐스팅(Broadcasting)가능   
ex) 3x1 + 1x3


In [ ]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [ ]:
b = np.array([[1], 
              [2]])

In [ ]:
a.shape, b.shape

((2, 3), (2, 1))

In [ ]:
a * b

array([[1, 2, 3],
       [4, 6, 8]])

In [ ]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [ ]:
b = np.array([1, 2, 3])

In [ ]:
a.shape, b.shape

((2, 3), (3,))

In [ ]:
a * b

array([[ 1,  4,  9],
       [ 2,  6, 12]])

브로드 캐스팅 연산 행열 예시)  
[1x4 + 4x1 행렬 연산 이미지 참고](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2Fc239jk%2FbtqCM8NKsXw%2FRhz8cdGI7PbE5KM5KX4ag0%2Fimg.png)

[3차원 브로드캐스팅 참고 ](http://www.astroml.org/_images/fig_broadcast_visual_1.png)

In [ ]:
Value = np.array([[1,2,3,4],[2,5,6,7],[8,9,10,11],[12,13,14,15]])
Value1 = np.array([1])
Value2 = np.array([3,3,3,3])
Value3 = np.array([4,5,6,7]).reshape(4,1)

In [ ]:
print(Value + Value1) #4x4 + 1

[[ 2  3  4  5]
 [ 3  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
print(Value + Value2) #4x4 + 1x4

[[ 4  5  6  7]
 [ 5  8  9 10]
 [11 12 13 14]
 [15 16 17 18]]


In [ ]:
print(Value2 + Value3) #1x4 + 4x1

[[ 7  7  7  7]
 [ 8  8  8  8]
 [ 9  9  9  9]
 [10 10 10 10]]


In [ ]:
# 4x1 + 1x4
Value3 + Value2

array([[ 7,  7,  7,  7],
       [ 8,  8,  8,  8],
       [ 9,  9,  9,  9],
       [10, 10, 10, 10]])

#[문제] 범주형 데이터 encoding
[단계1]
#### 1. 다음의 범주형 문자 객체를 만들고 소팅하기
  - 주방, 폰, 욕실, 거실 

#### 2. 문자열 andarry 값을 파라미터로 받아서 숫자로 인코딩하는 함수 정의하고, 실행 결과 출력하기
  - 문자를 0~n-1까지 숫자로 변경  


[단계2]
#### 3. 숫자로 변경한 값을 다시 one-hot 인코딩 형태로 바꾸기

### 문제 풀이
1. 범주형 문자열 객체를 만들고 소팅하기

In [ ]:
import numpy as np

In [ ]:
# 문자열 ndarray 객체 생성


In [ ]:
# e_lists 정렬하기


array(['거실', '욕실', '주방', '폰'], dtype='<U2')

2. 문자열을 숫자로 인코딩 하는 함수 만들기


####3. one-hot 인코딩 형태로 바꾸기
[해결방법1]


[해결방법2] np.zeros()로 2차원 배열을 만들고 적용

In [ ]:
label_num = np.array(encoding_label(e_lists))
label_num

array([2, 3, 1, 0])

In [ ]:
label_num.size

4

In [ ]:
one_hot = np.zeros((label_num.size, label_num.max()+1))
one_hot

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.arange(label_num.size)

array([0, 1, 2, 3])

In [ ]:
label_num

array([0, 1, 2, 3])

In [ ]:
one_hot[np.array([0,1,2,3]),np.array([0,1,2,3])]

array([0., 0., 0., 0.])

In [ ]:
one_hot[np.arange(label_num.size),label_num] = 1

In [ ]:
one_hot.astype(int)

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [1, 0, 0, 0]])